### ISSUE TITLE
Cross-Check 'File Manager' - 'EkaterinaKunskaya'

### ISSUE THREAD

**Issue by EkaterinaKunskaya** [rolling-scopes-school/support#954] opened 2024-02-12 22:53 UTC
1. A link to your deployed project
    - the task didn't involve a deployment
2. A link to the project repository on Github.
    - [EkaterinaKunskaya/node-file-manager/PR](https://github.com/EkaterinaKunskaya/node-file-manager/pull/1)
3. A link to the task
    - [Assignment: File Manager](https://github.com/AlreadyBored/nodejs-assignments/blob/main/assignments/file-manager/assignment.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - The checklist for evaluating the task is available in the Cross-Check: Review section
5. A screenshot of cross-checking marks
![image](https://github.com/rolling-scopes-school/support/assets/97041073/4d0e7be8-0e0b-4520-a9c6-34995d9c7ff7)
![image](https://github.com/rolling-scopes-school/support/assets/97041073/b2d8f1f5-83c1-4515-b79b-1b13b369b56b)

6. A final score after self-assessment, with comments
### Basic Scope
- General
    - [x] **+6** Application accepts username and prints proper message
    - [x] **+10** Application exits if user pressed `ctrl+c` or sent `.exit` command and proper message is printed
- Operations fail
    - [x]  **+20** Attempts to perform an operation on a non-existent file or work on a non-existent path result in the operation fail
    - [x]  **+10** Operation fail doesn't crash application
- Navigation & working directory operations implemented properly
    - [x]  **+10** Go upper from current directory
    - [x]  **+10** Go to dedicated folder from current directory
    - [x]  **+20** List all files and folders in current directory
- Basic operations with files implemented properly
    - [x]  **+10** Read file and print it's content in console
    - [x]  **+10** Create empty file
    - [x]  **+10** Rename file
    - [x]  **+10** Copy file
    - [x]  **+10** Move file
    - [x]  **+10** Delete file
- Operating system info (prints following information in console) implemented properly
    - [x]  **+6** Get EOL (default system End-Of-Line)
    - [x]  **+10** Get host machine CPUs info (overall amount of CPUS plus model and clock rate (in GHz) for each of them)
    - [x]  **+6** Get home directory
    - [x]  **+6** Get current *system user name* (Do not confuse with the username that is set when the application starts)
    - [x]  **+6** Get CPU architecture for which Node.js binary has compiled
- Hash calculation implemented properly
    - [x]  **+20** Calculate hash for file 
- Compress and decompress operations
    - [x]  **+20** Compress file (using Brotli algorithm)
    - [x]  **+20** Decompress file (using Brotli algorithm)

### Advanced Scope
- [x]  **+30** All operations marked as to be implemented using certain streams should be performed using Streams API
- [x]  **+20** No synchronous Node.js API with asynchronous analogues is used (e.g. not used `readFileSync` instead of `readFile`)  
- [x]  **+20** Codebase is written in ESM modules instead of CommonJS
- [x]  **+20** Codebase is separated (at least 7 modules)

Total score:**330/330**

7. A cross-check score of your Score 
**279/330**

**Comment by EternalRival** [comment] 2024-02-13 17:52
> @AlreadyBored, ~~I don't have the rights to change the label, so I'll just post the review here~~

# Scoring: File Manager (330/330)

## Notes

> @EkaterinaKunskaya, there are some notes for you here and below in the comments
> - When launching an application without the `username` argument, the application greets the user as `Anonymous` but says goodbye to him as `undefined`. I assume that the script for saying goodbye is slightly underdeveloped. The behavior of the application without the username argument is not regulated by the task, so I mention it separately.
> - The application has strange `prompt` behavior (`>` character at the beginning of the line while waiting for a command). The `prompt` character appears during input, not during command wait. To avoid this, you can manually call the `readlineInterface.prompt()` method while prompting the user to enter commands.

## Basic Scope

- General
  - [x] **+6** Application accepts username and prints proper message
  - [x] **+10** Application exits if user pressed `ctrl+c` or sent `.exit` command and proper message is printed
- Operations fail
  - [x] **+20** Attempts to perform an operation on a non-existent file or work on a non-existent path result in the operation fail
  - [x] **+10** Operation fail doesn't crash application
- Navigation & working directory operations implemented properly
  - [x] **+10** Go upper from current directory
  - [x] **+10** Go to dedicated folder from current directory
  - [x] **+20** List all files and folders in current directory
    > The `ls` command works according to the requirements, but there is a small remark. your `ls` command considers entities with type `symbolic-link` as entities with type `directory`, because the conditional construct `dirent.isFile() ? LIST_FILE : LIST_DIRECTORY`. Look at the other methods (`isFile`, `isDirectory`, `isSymbolicLink`, `isSocket`, etc.) and `switch..case` or something like that.
- Basic operations with files implemented properly
  - [x] **+10** Read file and print it's content in console
    > The command correctly outputs the contents of the file to the console. Names without spaces are supported (without quotes). Names with spaces are supported (with quotes). Unexpected behavior when quoting a file without a space in the name, but it seems that there was no need to check this kind of "edge case". I consider the point fulfilled.
  - [x] **+10** Create empty file
  - [x] **+10** Rename file
  - [x] **+10** Copy file
    > The specified file is copied to the specified folder according to the requirements, but there is a small remark. When copying to another folder, the `_copy` suffix is added to the file name. Technically, the requirements do not specify the name of the final file, so I don't consider it a violation (I assume it's a feature)
  - [x] **+10** Move file
  - [x] **+10** Delete file
- Operating system info (prints following information in console) implemented properly
  - [x] **+6** Get EOL (default system End-Of-Line)
  - [x] **+10** Get host machine CPUs info (overall amount of CPUS plus model and clock rate (in GHz) for each of them)
  - [x] **+6** Get home directory
  - [x] **+6** Get current _system user name_ (Do not confuse with the username that is set when the application starts)
  - [x] **+6** Get CPU architecture for which Node.js binary has compiled
- Hash calculation implemented properly
  - [x] **+20** Calculate hash for file
- Compress and decompress operations
  - [x] **+20** Compress file (using Brotli algorithm)
  - [x] **+20** Decompress file (using Brotli algorithm)

## Advanced Scope

- [x] **+30** All operations marked as to be implemented using certain streams should be performed using Streams API
- [x] **+20** No synchronous Node.js API with asynchronous analogues is used (e.g. not used `readFileSync` instead of `readFile`)
  > Only `fs.existsSync` is used in the project from Synchronous Api. `fsPromises.exists` (Promises Api) does not exist, and `fs.exists` (Callback Api) is deprecated. `fs.stat` and `fs.access` are not direct analogs of `fs.exists`. I consider the use of `fs.existsSync` to be acceptable. And in general, on one of the previous threads in the same task in a similar situation, the task curator gave the following answer. ![existsSync](https://i.imgur.com/cnodiTQ.png)
- [x] **+20** Codebase is written in ESM modules instead of CommonJS
- [x] **+20** Codebase is separated (at least 7 modules)

## Forfeits

- [ ] **-95% of total task score** Any external tools/libraries are used
- [ ] **-30% of total task score** Commits after deadline (except commits that affect only `Readme.md`, `.gitignore`, etc.)

**Comment by ThorsAngerVaNeT** [comment] 2024-02-13 18:24
@EternalRival so what is total score?

**Comment by EternalRival** [comment] 2024-02-13 18:26
> @EternalRival so what is total score?

fxd

330/330.

**Comment by Opty1712** [comment] 2024-02-14 07:28
congratulations!!!

**Comment by helenakrasnova** [comment] 2024-02-14 10:26
@ThorsAngerVaNeT could you pls udpate mark?

**Comment by ThorsAngerVaNeT** [comment] 2024-02-14 10:27
> @ThorsAngerVaNeT could you pls udpate mark?

Yes, sure. I was thinking to wait for all appellations to be completed...

**Comment by EkaterinaKunskaya** [comment] 2024-02-14 10:36
@helenakrasnova , @ThorsAngerVaNeT , thank's so much for your work!
@EternalRival , special thank you very much for the cool review)

**Comment by ThorsAngerVaNeT** [comment] 2024-02-14 10:36
Score was updated

**Closed as completed** 2024-02-14 10:36 UTC
Labels: ✅ review completed
